name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Minecraft 1.18 and above require Java 17
        java: [ 17 ]
        # Try Temurin and Zulu
        javadist: [ temurin, zulu ]
        # Build on Ubuntu and Windows
        os: [ ubuntu-latest, windows-latest ]
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2.5.0
        with:
          distribution: ${{ matrix.javadist }}
          java-version: ${{ matrix.java }}

      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
          # Daemon JVM options
          GRADLE_OPTS: -Xms4G -Xmx4G
        with:
          arguments: build --no-daemon --parallel --configure-on-demand

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts (Java ${{ matrix.java }} (${{ matrix.javadist }}) @ ${{ runner.os }})
          path: build/libs/
