name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Minecraft 1.18 and above require Java 17
        java: [ 17 ]
        # Build on Ubuntu and Windows
        os: [ ubuntu-latest, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: build --no-daemon --parallel --configure-on-demand -Dorg.gradle.jvmargs="-Xmx5Gm -Xms5G -XX:+UseParallelGC"

      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts (Java ${{ matrix.java }}@${{ runner.os }})
          path: build/libs/
